### ISSUE TITLE
"replacement transaction underpriced" error when calling two transactions in a row from different contract instances

### ISSUE THREAD

**Issue by Eugenpaul** [EthWorks/ethereum.rb#35]
There seems to be a problem with getting a valid nonce if I call the same contract from different instances. The log looks like this:
```
replacement transaction underpriced
<...>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ethereum.rb-6a921f96dfc1/lib/ethereum/client.rb:129:in `send_command'
<...>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ethereum.rb-6a921f96dfc1/lib/ethereum/client.rb:137:in `block (2 levels) in <class:Client>'
<...>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ethereum.rb-6a921f96dfc1/lib/ethereum/contract.rb:87:in `send_raw_transaction'
<...>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ethereum.rb-6a921f96dfc1/lib/ethereum/contract.rb:141:in `transact'
<...>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/ethereum.rb-6a921f96dfc1/lib/ethereum/contract.rb:235:in `block (2 levels) in create_function_proxies'
```
When I tried to [fix](https://github.com/EthWorks/ethereum.rb/pull/23) get_nonce by adding the missing argument to eth_get_transaction_count, I added "latest" as it was the default, and it looked like it worked. But "latest" doesn't take into account pending transactions. When I use the same contract instance -  global nonce in send_raw_transaction gets increased and the issue goes away. But when I use different contract instances - nonce turns out to be the same, because "latest" transaction_count doesn't change until the next block.
So should I refix this by making a PR with "pending" instead of "latest" in eth_get_transaction_count? At least for me it works, and I don't see anything that could be broken by this change.

**Comment by ngan** [comment]
BTW, even if we changed it to "pending" (which makes perfect sense), there's still a bug in go-ethereum that returns the incorrect count.
https://github.com/ethereum/go-ethereum/issues/2880

**Comment by ngan** [comment]
Ideal, it would be nice to be able to override/manage our own nonce.

**Comment by marekkirejczyk** [comment]
Fix merged:
https://github.com/EthWorks/ethereum.rb/commit/433a6e895abe69c688c4b525a56843564d15f254

Thx @kulerskim!

**Comment by juanfer** [comment]
Thanks @kulerskim for patching this. However, as @ngan said, bug in go-ethereum makes the patch useless (I updated ethereum.rb just to confirm it). Finally I had to face the problem creating a queu of transactions in database to be able to send several transactions from the same address, one after the former was mined.

**Comment by kulerskim** [comment]
@juanfer, fix allows you to pass your own nonce - that worked for us, at least temporarily. When go-ethereum is fixed, we'll just remove generating own nonce and hopefully `pending` will make the job then ;-)

**Comment by marekkirejczyk** [comment]
@juanfer @kulerskim Not sure if it is a bug in go ethereum. I think the intention is to send one transaction at a time. If you send multiple transactions you run into frontrunning problems (concurrency) and some transactions might be randomly mined and some not. Therefore you should propagate multiple transactions per block, only if you know what you are doing. Probably gasPrice manipulation is required to ensure the order.

**Comment by kulerskim** [comment]
@marekkirejczyk as far as I understand when you are using 'pending' count you should be able to put more than one transaction in the block, however, it still does not produce predictable and bulletproof nonce value. You might be right that it is not a bug, rather more general design issue.
